### ISSUE TITLE
String handling

### ISSUE THREAD

**Issue by VAdamec** [dfinninger/lita-cmd#4]
How to pass strings to scripts ? it always explode to args or make nasty looking thing like this:

$'\342\200\234test' and $'test\342\200\235'

is there any other way than use regexp in script to get it ?
Thanks in advance

**Comment by dfinninger** [comment]
Best I can offer is a flag: `url_encoded_spaces`
This would allow you to pass in `lita cmd test "a string"` as `lita cmd test a%20string`

Options are passed in as an array split on spaces. So removing the spaces with text is the easiest thing to do.

**Comment by sjernigan** [comment]
This is giving me a bit of trouble too.  Here's a simple fix.  Instead of 
irb> str         => "--env herbie -d \"test details with spaces\""
irb> str.split(" ")    => ["--env", "herbie", "-d", "\"test", "details", "with", "spaces\""]

try
irb> require 'csv'        => true
irb> CSV::parse_line(str, col_sep: ' ')      => ["--env", "herbie", "-d", "test details with spaces"]

**Comment by dfinninger** [comment]
Fixed by #14
